/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupplierRouteImport } from './routes/supplier'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlantCareRouteImport } from './routes/plant-care'
import { Route as NurseriesRouteImport } from './routes/nurseries'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BrowseHerbsRouteImport } from './routes/browse-herbs'
import { Route as BecomeASupplierRouteImport } from './routes/become-a-supplier'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupplierIndexRouteImport } from './routes/supplier.index'
import { Route as NurseriesIndexRouteImport } from './routes/nurseries.index'
import { Route as BrowseHerbsIndexRouteImport } from './routes/browse-herbs.index'
import { Route as SupplierProfileRouteImport } from './routes/supplier.profile'
import { Route as SupplierHerbsRouteImport } from './routes/supplier.herbs'
import { Route as SupplierBookingsRouteImport } from './routes/supplier.bookings'
import { Route as NurseriesIdRouteImport } from './routes/nurseries.$id'
import { Route as BrowseHerbsSlugRouteImport } from './routes/browse-herbs.$slug'

const SupplierRoute = SupplierRouteImport.update({
  id: '/supplier',
  path: '/supplier',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantCareRoute = PlantCareRouteImport.update({
  id: '/plant-care',
  path: '/plant-care',
  getParentRoute: () => rootRouteImport,
} as any)
const NurseriesRoute = NurseriesRouteImport.update({
  id: '/nurseries',
  path: '/nurseries',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseHerbsRoute = BrowseHerbsRouteImport.update({
  id: '/browse-herbs',
  path: '/browse-herbs',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeASupplierRoute = BecomeASupplierRouteImport.update({
  id: '/become-a-supplier',
  path: '/become-a-supplier',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierIndexRoute = SupplierIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupplierRoute,
} as any)
const NurseriesIndexRoute = NurseriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NurseriesRoute,
} as any)
const BrowseHerbsIndexRoute = BrowseHerbsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrowseHerbsRoute,
} as any)
const SupplierProfileRoute = SupplierProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SupplierRoute,
} as any)
const SupplierHerbsRoute = SupplierHerbsRouteImport.update({
  id: '/herbs',
  path: '/herbs',
  getParentRoute: () => SupplierRoute,
} as any)
const SupplierBookingsRoute = SupplierBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => SupplierRoute,
} as any)
const NurseriesIdRoute = NurseriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NurseriesRoute,
} as any)
const BrowseHerbsSlugRoute = BrowseHerbsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BrowseHerbsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-a-supplier': typeof BecomeASupplierRoute
  '/browse-herbs': typeof BrowseHerbsRouteWithChildren
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/login': typeof LoginRoute
  '/nurseries': typeof NurseriesRouteWithChildren
  '/plant-care': typeof PlantCareRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supplier': typeof SupplierRouteWithChildren
  '/browse-herbs/$slug': typeof BrowseHerbsSlugRoute
  '/nurseries/$id': typeof NurseriesIdRoute
  '/supplier/bookings': typeof SupplierBookingsRoute
  '/supplier/herbs': typeof SupplierHerbsRoute
  '/supplier/profile': typeof SupplierProfileRoute
  '/browse-herbs/': typeof BrowseHerbsIndexRoute
  '/nurseries/': typeof NurseriesIndexRoute
  '/supplier/': typeof SupplierIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-a-supplier': typeof BecomeASupplierRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/login': typeof LoginRoute
  '/plant-care': typeof PlantCareRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/browse-herbs/$slug': typeof BrowseHerbsSlugRoute
  '/nurseries/$id': typeof NurseriesIdRoute
  '/supplier/bookings': typeof SupplierBookingsRoute
  '/supplier/herbs': typeof SupplierHerbsRoute
  '/supplier/profile': typeof SupplierProfileRoute
  '/browse-herbs': typeof BrowseHerbsIndexRoute
  '/nurseries': typeof NurseriesIndexRoute
  '/supplier': typeof SupplierIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-a-supplier': typeof BecomeASupplierRoute
  '/browse-herbs': typeof BrowseHerbsRouteWithChildren
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/login': typeof LoginRoute
  '/nurseries': typeof NurseriesRouteWithChildren
  '/plant-care': typeof PlantCareRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supplier': typeof SupplierRouteWithChildren
  '/browse-herbs/$slug': typeof BrowseHerbsSlugRoute
  '/nurseries/$id': typeof NurseriesIdRoute
  '/supplier/bookings': typeof SupplierBookingsRoute
  '/supplier/herbs': typeof SupplierHerbsRoute
  '/supplier/profile': typeof SupplierProfileRoute
  '/browse-herbs/': typeof BrowseHerbsIndexRoute
  '/nurseries/': typeof NurseriesIndexRoute
  '/supplier/': typeof SupplierIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/become-a-supplier'
    | '/browse-herbs'
    | '/contact'
    | '/faqs'
    | '/login'
    | '/nurseries'
    | '/plant-care'
    | '/privacy'
    | '/signup'
    | '/sitemap.xml'
    | '/supplier'
    | '/browse-herbs/$slug'
    | '/nurseries/$id'
    | '/supplier/bookings'
    | '/supplier/herbs'
    | '/supplier/profile'
    | '/browse-herbs/'
    | '/nurseries/'
    | '/supplier/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/become-a-supplier'
    | '/contact'
    | '/faqs'
    | '/login'
    | '/plant-care'
    | '/privacy'
    | '/signup'
    | '/sitemap.xml'
    | '/browse-herbs/$slug'
    | '/nurseries/$id'
    | '/supplier/bookings'
    | '/supplier/herbs'
    | '/supplier/profile'
    | '/browse-herbs'
    | '/nurseries'
    | '/supplier'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/become-a-supplier'
    | '/browse-herbs'
    | '/contact'
    | '/faqs'
    | '/login'
    | '/nurseries'
    | '/plant-care'
    | '/privacy'
    | '/signup'
    | '/sitemap.xml'
    | '/supplier'
    | '/browse-herbs/$slug'
    | '/nurseries/$id'
    | '/supplier/bookings'
    | '/supplier/herbs'
    | '/supplier/profile'
    | '/browse-herbs/'
    | '/nurseries/'
    | '/supplier/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BecomeASupplierRoute: typeof BecomeASupplierRoute
  BrowseHerbsRoute: typeof BrowseHerbsRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  LoginRoute: typeof LoginRoute
  NurseriesRoute: typeof NurseriesRouteWithChildren
  PlantCareRoute: typeof PlantCareRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupplierRoute: typeof SupplierRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supplier': {
      id: '/supplier'
      path: '/supplier'
      fullPath: '/supplier'
      preLoaderRoute: typeof SupplierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plant-care': {
      id: '/plant-care'
      path: '/plant-care'
      fullPath: '/plant-care'
      preLoaderRoute: typeof PlantCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nurseries': {
      id: '/nurseries'
      path: '/nurseries'
      fullPath: '/nurseries'
      preLoaderRoute: typeof NurseriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse-herbs': {
      id: '/browse-herbs'
      path: '/browse-herbs'
      fullPath: '/browse-herbs'
      preLoaderRoute: typeof BrowseHerbsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-supplier': {
      id: '/become-a-supplier'
      path: '/become-a-supplier'
      fullPath: '/become-a-supplier'
      preLoaderRoute: typeof BecomeASupplierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/': {
      id: '/supplier/'
      path: '/'
      fullPath: '/supplier/'
      preLoaderRoute: typeof SupplierIndexRouteImport
      parentRoute: typeof SupplierRoute
    }
    '/nurseries/': {
      id: '/nurseries/'
      path: '/'
      fullPath: '/nurseries/'
      preLoaderRoute: typeof NurseriesIndexRouteImport
      parentRoute: typeof NurseriesRoute
    }
    '/browse-herbs/': {
      id: '/browse-herbs/'
      path: '/'
      fullPath: '/browse-herbs/'
      preLoaderRoute: typeof BrowseHerbsIndexRouteImport
      parentRoute: typeof BrowseHerbsRoute
    }
    '/supplier/profile': {
      id: '/supplier/profile'
      path: '/profile'
      fullPath: '/supplier/profile'
      preLoaderRoute: typeof SupplierProfileRouteImport
      parentRoute: typeof SupplierRoute
    }
    '/supplier/herbs': {
      id: '/supplier/herbs'
      path: '/herbs'
      fullPath: '/supplier/herbs'
      preLoaderRoute: typeof SupplierHerbsRouteImport
      parentRoute: typeof SupplierRoute
    }
    '/supplier/bookings': {
      id: '/supplier/bookings'
      path: '/bookings'
      fullPath: '/supplier/bookings'
      preLoaderRoute: typeof SupplierBookingsRouteImport
      parentRoute: typeof SupplierRoute
    }
    '/nurseries/$id': {
      id: '/nurseries/$id'
      path: '/$id'
      fullPath: '/nurseries/$id'
      preLoaderRoute: typeof NurseriesIdRouteImport
      parentRoute: typeof NurseriesRoute
    }
    '/browse-herbs/$slug': {
      id: '/browse-herbs/$slug'
      path: '/$slug'
      fullPath: '/browse-herbs/$slug'
      preLoaderRoute: typeof BrowseHerbsSlugRouteImport
      parentRoute: typeof BrowseHerbsRoute
    }
  }
}

interface BrowseHerbsRouteChildren {
  BrowseHerbsSlugRoute: typeof BrowseHerbsSlugRoute
  BrowseHerbsIndexRoute: typeof BrowseHerbsIndexRoute
}

const BrowseHerbsRouteChildren: BrowseHerbsRouteChildren = {
  BrowseHerbsSlugRoute: BrowseHerbsSlugRoute,
  BrowseHerbsIndexRoute: BrowseHerbsIndexRoute,
}

const BrowseHerbsRouteWithChildren = BrowseHerbsRoute._addFileChildren(
  BrowseHerbsRouteChildren,
)

interface NurseriesRouteChildren {
  NurseriesIdRoute: typeof NurseriesIdRoute
  NurseriesIndexRoute: typeof NurseriesIndexRoute
}

const NurseriesRouteChildren: NurseriesRouteChildren = {
  NurseriesIdRoute: NurseriesIdRoute,
  NurseriesIndexRoute: NurseriesIndexRoute,
}

const NurseriesRouteWithChildren = NurseriesRoute._addFileChildren(
  NurseriesRouteChildren,
)

interface SupplierRouteChildren {
  SupplierBookingsRoute: typeof SupplierBookingsRoute
  SupplierHerbsRoute: typeof SupplierHerbsRoute
  SupplierProfileRoute: typeof SupplierProfileRoute
  SupplierIndexRoute: typeof SupplierIndexRoute
}

const SupplierRouteChildren: SupplierRouteChildren = {
  SupplierBookingsRoute: SupplierBookingsRoute,
  SupplierHerbsRoute: SupplierHerbsRoute,
  SupplierProfileRoute: SupplierProfileRoute,
  SupplierIndexRoute: SupplierIndexRoute,
}

const SupplierRouteWithChildren = SupplierRoute._addFileChildren(
  SupplierRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BecomeASupplierRoute: BecomeASupplierRoute,
  BrowseHerbsRoute: BrowseHerbsRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  LoginRoute: LoginRoute,
  NurseriesRoute: NurseriesRouteWithChildren,
  PlantCareRoute: PlantCareRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupplierRoute: SupplierRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
